import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NextTopLoader from 'nextjs-toploader';
import '../../public/css/style.css'
import AppNavbar from "@/component/header/app-navbar";
import TopMenu from "@/component/header/top-menu";
import FooterComponent from "@/component/header/footer-component";


// Load the fonts
const geistSans = Geist({ subsets: ["latin"], variable: "--font-geist" });
const geistMono = Geist_Mono({ subsets: ["latin"], variable: "--font-geist-mono" });
const poppins = Poppins({ subsets: ["latin"], variable: "--font-poppins", weight: ["400", "700"] });

export const metadata = {
    title: "softDev uttom kumar",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}>
        <NextTopLoader
            color="#2299DD"
            showSpinner={false}
        />
        <div className="block mb-12 lg:flex lg:mb-0  ">
            <div className="py-2 z-50 px-5 w-full lg:w-[4%] bg-white fixed lg:h-[100vh] lg:px-0 lg:top-0 lg:left-0 lg:text-center top-0">
                <TopMenu />
            </div>
        </div>
        <div className="block lg:flex ">
            <div className="bg-white z-40 shadow w-full lg:bg-transparent lg:w-[20%] fixed lg:h-[100vh] lg:top-0 lg:left-[4%] lg:text-center bottom-0 lg:overflow-auto scrollBar ">
               <AppNavbar />
            </div>
            <div className="w-full lg:w-[76%] lg:ml-[24%] px-5">
                {children}
                <FooterComponent />
            </div>
        </div>
        </body>
        </html>
    );
}